//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityInterface.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public int Deptno { get; set; }
        public string Dname { get; set; }
        public string Dlocation { get; set; }
    }
}
