//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityInterface.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Empno { get; set; }
        public string Ename { get; set; }
        public string Designation { get; set; }
        public Nullable<decimal> salary { get; set; }
        public Nullable<int> Deptno { get; set; }
    }
}
